In [1]:
from datetime import timedelta
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from itertools import chain, combinations, permutations
import numpy as np
import os
from io import StringIO

In [2]:
df_original = pd.read_parquet('../../Sonar/seatunnel_all_information.parquet')

In [3]:
directory_path = 'D:\origin-source-code-bill\models\KMeans\combia'

In [4]:
df_original[0:2]

,begin_sha,end_sha,commits,additions,deletions,changed_files,total_time,begin_time,end_time,begin_Dispensables,begin_Bloaters,begin_Change Preventers,begin_Couplers,begin_Object-Orientation Abusers,end_Dispensables,end_Bloaters,end_Change Preventers,end_Couplers,end_Object-Orientation Abusers
0,84be0f9fd057b1680d001de38802ce1c28d79f04,9a2efa51c7180b369ecfea17efaae813d9d0bfc5,1,10,4,3,3 days 01:27:48,2023-06-02T07:22:03Z,2023-06-05T08:49:51Z,500.0,262.0,262.0,304.0,304.0,500.0,261.0,261.0,304.0,693.0
1,84be0f9fd057b1680d001de38802ce1c28d79f04,5e03d22d6cb5bfdaf941b7749e0a313bd6ab2f86,1,2,1,1,3 days 04:15:10,2023-06-02T05:07:40Z,2023-06-05T09:22:50Z,500.0,262.0,262.0,304.0,304.0,501.0,262.0,262.0,304.0,693.0

In [5]:
df = pd.read_pickle("../KMeans/lable/lables_2.pkl")

In [6]:
df = df.rename(columns={
    0 : 'name',
    1 : 'group',
    2 : 'score',
    3 : 'lables'
})

In [7]:
df.head(2)

,name,group,score,lables
0,"[begin_Bloaters, begin_Change Preventers, begi...",2,0.7291,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,"[begin_Bloaters, begin_Change Preventers, begi...",2,0.7190,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [8]:
df_explode = df.explode('name')
df_explode_lables = df.explode('lables')
df_explode_lables

                                                 name  group   score lables
0   [begin_Bloaters, begin_Change Preventers, begi...      2  0.7291      1
0   [begin_Bloaters, begin_Change Preventers, begi...      2  0.7291      1
0   [begin_Bloaters, begin_Change Preventers, begi...      2  0.7291      1
0   [begin_Bloaters, begin_Change Preventers, begi...      2  0.7291      1
0   [begin_Bloaters, begin_Change Preventers, begi...      2  0.7291      1
..                                                ...    ...     ...    ...
46                                    [changed_files]      2  0.9907      0
46                                    [changed_files]      2  0.9907      0
46                                    [changed_files]      2  0.9907      0
46                                    [changed_files]      2  0.9907      0
46                                    [changed_files]      2  0.9907      0

[50196 rows x 4 columns]

In [9]:
pkl_files = [f for f in os.listdir(directory_path) if f.endswith('.pkl')]

In [10]:
pkl_files

["['begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers'].pkl",
 "['begin_Bloaters', 'begin_Change Preventers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Bloaters', 'begin_Change Preventers'].pkl",
 "['begin_Bloaters', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Bloaters', 'begin_Couplers'].pkl",
 "['begin_Bloaters', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Bloaters'].pkl",
 "['begin_Change Preventers', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Change Preventers', 'begin_Couplers'].pkl",
 "['begin_Change Preventers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Change Preventers'].pkl",
 "['begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Couplers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters', 'begin_Couplers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables', 'begin_Bloaters'].pkl",
 "['begin_Dispensables', 'begin_Change Preventers', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables', 'begin_Change Preventers', 'begin_Couplers'].pkl",
 "['begin_Dispensables', 'begin_Change Preventers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables', 'begin_Change Preventers'].pkl",
 "['begin_Dispensables', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables', 'begin_Couplers'].pkl",
 "['begin_Dispensables', 'begin_Object-Orientation Abusers'].pkl",
 "['begin_Dispensables'].pkl",
 "['begin_Object-Orientation Abusers'].pkl",
 "['changed_files', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Bloaters', 'begin_Change Preventers'].pkl",
 "['changed_files', 'begin_Bloaters', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Bloaters'].pkl",
 "['changed_files', 'begin_Change Preventers', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Change Preventers'].pkl",
 "['changed_files', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers'].pkl",
 "['changed_files', 'begin_Dispensables', 'begin_Bloaters', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Dispensables', 'begin_Bloaters'].pkl",
 "['changed_files', 'begin_Dispensables', 'begin_Change Preventers', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Dispensables', 'begin_Change Preventers'].pkl",
 "['changed_files', 'begin_Dispensables', 'begin_Couplers'].pkl",
 "['changed_files', 'begin_Dispensables'].pkl",
 "['changed_files'].pkl"]

In [11]:
for csv_file in pkl_files:
    file_path = os.path.join(directory_path, csv_file)
    print("file :::" , file_path)
    df_col_combined = pd.read_pickle(file_path)
    print("DF ::" , df_col_combined)

file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl
DF ::       begin_Bloaters  begin_Change Preventers  begin_Couplers  \
0              262.0                    262.0           304.0
1              262.0                    262.0           304.0
2              262.0                    262.0           304.0
3              262.0                    262.0           304.0
4              261.0                    261.0           304.0
...              ...                      ...             ...
1063            14.0                     14.0             7.0
1064            12.0                     12.0             8.0
1065            12.0                     12.0             8.0
1066             3.0                      3.0             3.0
1067             3.0                      3.0             3.0

      begin_Object-Orientation Abusers
0                                304.0
1                                304.0
2                                304.0
3                                304.0
4                                304.0
...                                ...
1063                               7.0
1064                               8.0
1065                               8.0
1066                               3.0
1067                               3.0

[1068 rows x 4 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers'].pkl
DF ::       begin_Bloaters  begin_Change Preventers  begin_Couplers
0              262.0                    262.0           304.0
1              262.0                    262.0           304.0
2              262.0                    262.0           304.0
3              262.0                    262.0           304.0
4              261.0                    261.0           304.0
...              ...                      ...             ...
1063            14.0                     14.0             7.0
1064            12.0                     12.0             8.0
1065            12.0                     12.0             8.0
1066             3.0                      3.0             3.0
1067             3.0                      3.0             3.0

[1068 rows x 3 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters', 'begin_Change Preventers', 'begin_Object-Orientation Abusers'].pkl
DF ::       begin_Bloaters  begin_Change Preventers  \
0              262.0                    262.0
1              262.0                    262.0
2              262.0                    262.0
3              262.0                    262.0
4              261.0                    261.0
...              ...                      ...
1063            14.0                     14.0
1064            12.0                     12.0
1065            12.0                     12.0
1066             3.0                      3.0
1067             3.0                      3.0

      begin_Object-Orientation Abusers
0                                304.0
1                                304.0
2                                304.0
3                                304.0
4                                304.0
...                                ...
1063                               7.0
1064                               8.0
1065                               8.0
1066                               3.0
1067                               3.0

[1068 rows x 3 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters', 'begin_Change Preventers'].pkl
DF ::       begin_Bloaters  begin_Change Preventers
0              262.0                    262.0
1              262.0                    262.0
2              262.0                    262.0
3              262.0                    262.0
4              261.0                    261.0
...              ...                      ...
1063            14.0                     14.0
1064            12.0                     12.0
1065            12.0                     12.0
1066             3.0                      3.0
1067             3.0                      3.0

[1068 rows x 2 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl
DF ::       begin_Bloaters  begin_Couplers  begin_Object-Orientation Abusers
0              262.0           304.0                             304.0
1              262.0           304.0                             304.0
2              262.0           304.0                             304.0
3              262.0           304.0                             304.0
4              261.0           304.0                             304.0
...              ...             ...                               ...
1063            14.0             7.0                               7.0
1064            12.0             8.0                               8.0
1065            12.0             8.0                               8.0
1066             3.0             3.0                               3.0
1067             3.0             3.0                               3.0

[1068 rows x 3 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters', 'begin_Couplers'].pkl
DF ::       begin_Bloaters  begin_Couplers
0              262.0           304.0
1              262.0           304.0
2              262.0           304.0
3              262.0           304.0
4              261.0           304.0
...              ...             ...
1063            14.0             7.0
1064            12.0             8.0
1065            12.0             8.0
1066             3.0             3.0
1067             3.0             3.0

[1068 rows x 2 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters', 'begin_Object-Orientation Abusers'].pkl
DF ::       begin_Bloaters  begin_Object-Orientation Abusers
0              262.0                             304.0
1              262.0                             304.0
2              262.0                             304.0
3              262.0                             304.0
4              261.0                             304.0
...              ...                               ...
1063            14.0                               7.0
1064            12.0                               8.0
1065            12.0                               8.0
1066             3.0                               3.0
1067             3.0                               3.0

[1068 rows x 2 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Bloaters'].pkl
DF ::       begin_Bloaters
0              262.0
1              262.0
2              262.0
3              262.0
4              261.0
...              ...
1063            14.0
1064            12.0
1065            12.0
1066             3.0
1067             3.0

[1068 rows x 1 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Change Preventers', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl
DF ::       begin_Change Preventers  begin_Couplers  \
0                       262.0           304.0
1                       262.0           304.0
2                       262.0           304.0
3                       262.0           304.0
4                       261.0           304.0
...                       ...             ...
1063                     14.0             7.0
1064                     12.0             8.0
1065                     12.0             8.0
1066                      3.0             3.0
1067                      3.0             3.0

      begin_Object-Orientation Abusers
0                                304.0
1                                304.0
2                                304.0
3                                304.0
4                                304.0
...                                ...
1063                               7.0
1064                               8.0
1065                               8.0
1066                               3.0
1067                               3.0

[1068 rows x 3 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Change Preventers', 'begin_Couplers'].pkl
DF ::       begin_Change Preventers  begin_Couplers
0                       262.0           304.0
1                       262.0           304.0
2                       262.0           304.0
3                       262.0           304.0
4                       261.0           304.0
...                       ...             ...
1063                     14.0             7.0
1064                     12.0             8.0
1065                     12.0             8.0
1066                      3.0             3.0
1067                      3.0             3.0

[1068 rows x 2 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Change Preventers', 'begin_Object-Orientation Abusers'].pkl
DF ::       begin_Change Preventers  begin_Object-Orientation Abusers
0                       262.0                             304.0
1                       262.0                             304.0
2                       262.0                             304.0
3                       262.0                             304.0
4                       261.0                             304.0
...                       ...                               ...
1063                     14.0                               7.0
1064                     12.0                               8.0
1065                     12.0                               8.0
1066                      3.0                               3.0
1067                      3.0                               3.0

[1068 rows x 2 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Change Preventers'].pkl
DF ::       begin_Change Preventers
0                       262.0
1                       262.0
2                       262.0
3                       262.0
4                       261.0
...                       ...
1063                     14.0
1064                     12.0
1065                     12.0
1066                      3.0
1067                      3.0

[1068 rows x 1 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Couplers', 'begin_Object-Orientation Abusers'].pkl
DF ::       begin_Couplers  begin_Object-Orientation Abusers
0              304.0                             304.0
1              304.0                             304.0
2              304.0                             304.0
3              304.0                             304.0
4              304.0                             304.0
...              ...                               ...
1063             7.0                               7.0
1064             8.0                               8.0
1065             8.0                               8.0
1066             3.0                               3.0
1067             3.0                               3.0

[1068 rows x 2 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Couplers'].pkl
DF ::       begin_Couplers
0              304.0
1              304.0
2              304.0
3              304.0
4              304.0
...              ...
1063             7.0
1064             8.0
1065             8.0
1066             3.0
1067             3.0

[1068 rows x 1 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl
DF ::      begin_Dispensables  begin_Bloaters  begin_Change Preventers  \
0                 500.0           262.0                    262.0
1                 500.0           262.0                    262.0
2                 500.0           262.0                    262.0
3                 500.0           262.0                    262.0
4                 499.0           261.0                    261.0
...                 ...             ...                      ...
1063               16.0            14.0                     14.0
1064               14.0            12.0                     12.0
1065               14.0            12.0                     12.0
1066                2.0             3.0                      3.0
1067                2.0             3.0                      3.0

      begin_Couplers  begin_Object-Orientation Abusers
0              304.0                             304.0
1              304.0                             304.0
2              304.0                             304.0
3              304.0                             304.0
4              304.0                             304.0
...              ...                               ...
1063             7.0                               7.0
1064             8.0                               8.0
1065             8.0                               8.0
1066             3.0                               3.0
1067             3.0                               3.0

[1068 rows x 5 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Couplers'].pkl
DF ::      begin_Dispensables  begin_Bloaters  begin_Change Preventers  \
0                 500.0           262.0                    262.0
1                 500.0           262.0                    262.0
2                 500.0           262.0                    262.0
3                 500.0           262.0                    262.0
4                 499.0           261.0                    261.0
...                 ...             ...                      ...
1063               16.0            14.0                     14.0
1064               14.0            12.0                     12.0
1065               14.0            12.0                     12.0
1066                2.0             3.0                      3.0
1067                2.0             3.0                      3.0

      begin_Couplers
0              304.0
1              304.0
2              304.0
3              304.0
4              304.0
...              ...
1063             7.0
1064             8.0
1065             8.0
1066             3.0
1067             3.0

[1068 rows x 4 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers', 'begin_Object-Orientation Abusers'].pkl
DF ::      begin_Dispensables  begin_Bloaters  begin_Change Preventers  \
0                 500.0           262.0                    262.0
1                 500.0           262.0                    262.0
2                 500.0           262.0                    262.0
3                 500.0           262.0                    262.0
4                 499.0           261.0                    261.0
...                 ...             ...                      ...
1063               16.0            14.0                     14.0
1064               14.0            12.0                     12.0
1065               14.0            12.0                     12.0
1066                2.0             3.0                      3.0
1067                2.0             3.0                      3.0

      begin_Object-Orientation Abusers
0                                304.0
1                                304.0
2                                304.0
3                                304.0
4                                304.0
...                                ...
1063                               7.0
1064                               8.0
1065                               8.0
1066                               3.0
1067                               3.0

[1068 rows x 4 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters', 'begin_Change Preventers'].pkl
DF ::      begin_Dispensables  begin_Bloaters  begin_Change Preventers
0                 500.0           262.0                    262.0
1                 500.0           262.0                    262.0
2                 500.0           262.0                    262.0
3                 500.0           262.0                    262.0
4                 499.0           261.0                    261.0
...                 ...             ...                      ...
1063               16.0            14.0                     14.0
1064               14.0            12.0                     12.0
1065               14.0            12.0                     12.0
1066                2.0             3.0                      3.0
1067                2.0             3.0                      3.0

[1068 rows x 3 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters', 'begin_Couplers', 'begin_Object-Orientation Abusers'].pkl
DF ::      begin_Dispensables  begin_Bloaters  begin_Couplers  \
0                 500.0           262.0           304.0
1                 500.0           262.0           304.0
2                 500.0           262.0           304.0
3                 500.0           262.0           304.0
4                 499.0           261.0           304.0
...                 ...             ...             ...
1063               16.0            14.0             7.0
1064               14.0            12.0             8.0
1065               14.0            12.0             8.0
1066                2.0             3.0             3.0
1067                2.0             3.0             3.0

      begin_Object-Orientation Abusers
0                                304.0
1                                304.0
2                                304.0
3                                304.0
4                                304.0
...                                ...
1063                               7.0
1064                               8.0
1065                               8.0
1066                               3.0
1067                               3.0

[1068 rows x 4 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters', 'begin_Couplers'].pkl
DF ::      begin_Dispensables  begin_Bloaters  begin_Couplers
0                 500.0           262.0           304.0
1                 500.0           262.0           304.0
2                 500.0           262.0           304.0
3                 500.0           262.0           304.0
4                 499.0           261.0           304.0
...                 ...             ...             ...
1063               16.0            14.0             7.0
1064               14.0            12.0             8.0
1065               14.0            12.0             8.0
1066                2.0             3.0             3.0
1067                2.0             3.0             3.0

[1068 rows x 3 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters', 'begin_Object-Orientation Abusers'].pkl
DF ::      begin_Dispensables  begin_Bloaters  begin_Object-Orientation Abusers
0                 500.0           262.0                             304.0
1                 500.0           262.0                             304.0
2                 500.0           262.0                             304.0
3                 500.0           262.0                             304.0
4                 499.0           261.0                             304.0
...                 ...             ...                               ...
1063               16.0            14.0                               7.0
1064               14.0            12.0                               8.0
1065               14.0            12.0                               8.0
1066                2.0             3.0                               3.0
1067                2.0             3.0                               3.0

[1068 rows x 3 columns]
file ::: D:\origin-source-code-bill\models\KMeans\combia\['begin_Dispensables', 'begin_Bloaters'].pkl

In [12]:
df_col_combined

      changed_files
0                 3
1                 1
2                 9
3                 3
4                80
...             ...
1063             12
1064             16
1065              9
1066             27
1067              1

[1068 rows x 1 columns]

In [13]:
df_explode_lables['name']

0     [begin_Bloaters, begin_Change Preventers, begi...
0     [begin_Bloaters, begin_Change Preventers, begi...
0     [begin_Bloaters, begin_Change Preventers, begi...
0     [begin_Bloaters, begin_Change Preventers, begi...
0     [begin_Bloaters, begin_Change Preventers, begi...
                            ...
46                                      [changed_files]
46                                      [changed_files]
46                                      [changed_files]
46                                      [changed_files]
46                                      [changed_files]
Name: name, Length: 50196, dtype: object

In [14]:
merged_df = pd.merge(df1, df2, left_on=df1.columns, right_on='name', how='inner')
merged_df

NameError: name 'df1' is not defined

In [ ]:
import pandas as pd

# Your DataFrame
data = {
    'name': [['begin_B', 'begin_C_P'], ['begin_Bloaters']],
    'lables': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
}

df = pd.DataFrame(data)
print("==========================")
print(df)
print(df.iterrows())
print("==========================")


# Loop through rows and extract data from the first column
# for index, row in df.iterrows():
#     print("INDEX ::" , index)
#     first_column_data = row[1]
#     first_column_data = pd.DataFrame(first_column_data)
#     first_column_data.explode(first_column_data)
#     print(f"Data from first column in row {index}: {first_column_data}")

In [15]:
# List to store exploded data
exploded_data = []

# Loop through rows and extract data from the first column
for index, row in df.iterrows():
    print("INDEX ::" , index)
    first_column_data = row
    print("ROW :::" , first_column_data)
    exploded_column = pd.DataFrame(first_column_data)
    exploded_column = exploded_column.T
    print("================")
    print(exploded_column)
    print("================")
    
    exploded_column.explode(['lables'])
    # exploded_column.rename(columns={ 0:'name'}, inplace=True)
    print("EXPLOED :::", exploded_column)
    # exploded_column.explode()
    print("================")
    # print(exploded_data)
    # exploded_data.append(exploded_column)
    # print("CONCAT :::" , exploded_data)

INDEX :: 0
ROW ::: name      [begin_Bloaters, begin_Change Preventers, begi...
group                                                     2
score                                                0.7291
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 0, dtype: object
================
                                                name group   score  \
0  [begin_Bloaters, begin_Change Preventers, begi...     2  0.7291

                                              lables
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                 name group   score  \
0  [begin_Bloaters, begin_Change Preventers, begi...     2  0.7291

                                              lables
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 1
ROW ::: name      [begin_Bloaters, begin_Change Preventers, begi...
group                                                     2
score                                                 0.719
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 1, dtype: object
================
                                                name group  score  \
1  [begin_Bloaters, begin_Change Preventers, begi...     2  0.719

                                              lables
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                 name group  score  \
1  [begin_Bloaters, begin_Change Preventers, begi...     2  0.719

                                              lables
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 2
ROW ::: name      [begin_Bloaters, begin_Change Preventers, begi...
group                                                     2
score                                                 0.719
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 2, dtype: object
================
                                                name group  score  \
2  [begin_Bloaters, begin_Change Preventers, begi...     2  0.719

                                              lables
2  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                 name group  score  \
2  [begin_Bloaters, begin_Change Preventers, begi...     2  0.719

                                              lables
2  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 3
ROW ::: name              [begin_Bloaters, begin_Change Preventers]
group                                                     2
score                                                0.6989
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 3, dtype: object
================
                                        name group   score  \
3  [begin_Bloaters, begin_Change Preventers]     2  0.6989

                                              lables
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                         name group   score  \
3  [begin_Bloaters, begin_Change Preventers]     2  0.6989

                                              lables
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 4
ROW ::: name      [begin_Bloaters, begin_Couplers, begin_Object-...
group                                                     2
score                                                0.7392
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 4, dtype: object
================
                                                name group   score  \
4  [begin_Bloaters, begin_Couplers, begin_Object-...     2  0.7392

                                              lables
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                 name group   score  \
4  [begin_Bloaters, begin_Couplers, begin_Object-...     2  0.7392

                                              lables
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 5
ROW ::: name                       [begin_Bloaters, begin_Couplers]
group                                                     2
score                                                0.7291
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 5, dtype: object
================
                               name group   score  \
5  [begin_Bloaters, begin_Couplers]     2  0.7291

                                              lables
5  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                name group   score  \
5  [begin_Bloaters, begin_Couplers]     2  0.7291

                                              lables
5  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 6
ROW ::: name      [begin_Bloaters, begin_Object-Orientation Abus...
group                                                     2
score                                                0.7291
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 6, dtype: object
================
                                                name group   score  \
6  [begin_Bloaters, begin_Object-Orientation Abus...     2  0.7291

                                              lables
6  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                 name group   score  \
6  [begin_Bloaters, begin_Object-Orientation Abus...     2  0.7291

                                              lables
6  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 7
ROW ::: name                                       [begin_Bloaters]
group                                                     2
score                                                0.6989
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 7, dtype: object
================
               name group   score  \
7  [begin_Bloaters]     2  0.6989

                                              lables
7  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                name group   score  \
7  [begin_Bloaters]     2  0.6989

                                              lables
7  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 8
ROW ::: name      [begin_Change Preventers, begin_Couplers, begi...
group                                                     2
score                                                0.7392
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 8, dtype: object
================
                                                name group   score  \
8  [begin_Change Preventers, begin_Couplers, begi...     2  0.7392

                                              lables
8  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                 name group   score  \
8  [begin_Change Preventers, begin_Couplers, begi...     2  0.7392

                                              lables
8  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 9
ROW ::: name              [begin_Change Preventers, begin_Couplers]
group                                                     2
score                                                0.7291
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 9, dtype: object
================
                                        name group   score  \
9  [begin_Change Preventers, begin_Couplers]     2  0.7291

                                              lables
9  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                         name group   score  \
9  [begin_Change Preventers, begin_Couplers]     2  0.7291

                                              lables
9  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 10
ROW ::: name      [begin_Change Preventers, begin_Object-Orienta...
group                                                     2
score                                                0.7291
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 10, dtype: object
================
                                                 name group   score  \
10  [begin_Change Preventers, begin_Object-Orienta...     2  0.7291

                                               lables
10  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                  name group   score  \
10  [begin_Change Preventers, begin_Object-Orienta...     2  0.7291

                                               lables
10  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 11
ROW ::: name                              [begin_Change Preventers]
group                                                     2
score                                                0.6989
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 11, dtype: object
================
                         name group   score  \
11  [begin_Change Preventers]     2  0.6989

                                               lables
11  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                          name group   score  \
11  [begin_Change Preventers]     2  0.6989

                                               lables
11  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 12
ROW ::: name      [begin_Couplers, begin_Object-Orientation Abus...
group                                                     2
score                                                0.7614
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 12, dtype: object
================
                                                 name group   score  \
12  [begin_Couplers, begin_Object-Orientation Abus...     2  0.7614

                                               lables
12  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                  name group   score  \
12  [begin_Couplers, begin_Object-Orientation Abus...     2  0.7614

                                               lables
12  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 13
ROW ::: name                                       [begin_Couplers]
group                                                     2
score                                                0.7614
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 13, dtype: object
================
                name group   score  \
13  [begin_Couplers]     2  0.7614

                                               lables
13  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                 name group   score  \
13  [begin_Couplers]     2  0.7614

                                               lables
13  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 14
ROW ::: name      [begin_Dispensables, begin_Bloaters, begin_Cha...
group                                                     2
score                                                0.7091
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 14, dtype: object
================
                                                 name group   score  \
14  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.7091

                                               lables
14  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                  name group   score  \
14  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.7091

                                               lables
14  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 15
ROW ::: name      [begin_Dispensables, begin_Bloaters, begin_Cha...
group                                                     2
score                                                0.6954
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 15, dtype: object
================
                                                 name group   score  \
15  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.6954

                                               lables
15  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                  name group   score  \
15  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.6954

                                               lables
15  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 16
ROW ::: name      [begin_Dispensables, begin_Bloaters, begin_Cha...
group                                                     2
score                                                0.6954
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 16, dtype: object
================
                                                 name group   score  \
16  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.6954

                                               lables
16  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                  name group   score  \
16  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.6954

                                               lables
16  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 17
ROW ::: name      [begin_Dispensables, begin_Bloaters, begin_Cha...
group                                                     2
score                                                0.6698
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 17, dtype: object
================
                                                 name group   score  \
17  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.6698

                                               lables
17  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                  name group   score  \
17  [begin_Dispensables, begin_Bloaters, begin_Cha...     2  0.6698

                                               lables
17  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 18
ROW ::: name      [begin_Dispensables, begin_Bloaters, begin_Cou...
group                                                     2
score                                                0.7129
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 18, dtype: object
================
                                                 name group   score  \
18  [begin_Dispensables, begin_Bloaters, begin_Cou...     2  0.7129

                                               lables
18  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                  name group   score  \
18  [begin_Dispensables, begin_Bloaters, begin_Cou...     2  0.7129

                                               lables
18  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 19
ROW ::: name      [begin_Dispensables, begin_Bloaters, begin_Cou...
group                                                     2
score                                                0.6962
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 19, dtype: object
================
                                                 name group   score  \
19  [begin_Dispensables, begin_Bloaters, begin_Cou...     2  0.6962

                                               lables
19  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                  name group   score  \
19  [begin_Dispensables, begin_Bloaters, begin_Cou...     2  0.6962

                                               lables
19  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 20
ROW ::: name      [begin_Dispensables, begin_Bloaters, begin_Obj...
group                                                     2
score                                                0.6962
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 20, dtype: object
================
                                                 name group   score  \
20  [begin_Dispensables, begin_Bloaters, begin_Obj...     2  0.6962

                                               lables
20  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                                  name group   score  \
20  [begin_Dispensables, begin_Bloaters, begin_Obj...     2  0.6962

                                               lables
20  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 21
ROW ::: name                   [begin_Dispensables, begin_Bloaters]
group                                                     2
score                                                0.6568
lables    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
Name: 21, dtype: object
================
                                    name group   score  \
21  [begin_Dispensables, begin_Bloaters]     2  0.6568

                                               lables
21  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
EXPLOED :::                                     name group   score  \
21  [begin_Dispensables, begin_Bloaters]     2  0.6568

                                               lables
21  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
================
INDEX :: 22
ROW ::: name      [begin_Dispensables, begin_Change Preventers, ...
group                                                     2
score                                                0.7129
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 22, dtype: object
================
                                                 name group   score  \
22  [begin_Dispensables, begin_Change Preventers, ...     2  0.7129

                                               lables
22  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                  name group   score  \
22  [begin_Dispensables, begin_Change Preventers, ...     2  0.7129

                                               lables
22  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 23
ROW ::: name      [begin_Dispensables, begin_Change Preventers, ...
group                                                     2
score                                                0.6962
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 23, dtype: object
================
                                                 name group   score  \
23  [begin_Dispensables, begin_Change Preventers, ...     2  0.6962

                                               lables
23  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
EXPLOED :::                                                  name group   score  \
23  [begin_Dispensables, begin_Change Preventers, ...     2  0.6962

                                               lables
23  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
================
INDEX :: 24
ROW ::: name      [begin_Dispensables, begin_Change Preventers, ...
group                                                     2
score                                                0.6962
lables    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 24, dtype: object
================
                                                 name group   score  \

In [16]:
exploded_column = pd.DataFrame(first_column_data)
exploded_column

                                                       46
name                                      [changed_files]
group                                                   2
score                                              0.9907
lables  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [17]:
exploded_column.T

,name,group,score,lables
46,[changed_files],2,0.9907,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [18]:
exploded_column

                                                       46
name                                      [changed_files]
group                                                   2
score                                              0.9907
lables  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [19]:
exploded_column.explode(1)

KeyError: 1